@startuml
title Smart Home Component Diagram

left to right direction
!include <C4/C4_Container>


Person(user, "Пользователь", "Пользователь приложение")

System_Boundary(SmartHomeSystem, "Smart Home") {

System_Boundary(web_application, "Веб приложение") {
    Container(api_gateway, "API Gateway", "", "Управляет запросами пользователей и маршрутизацией к веб-приложению")
    Container(web_app, "Веб-приложение", "Java, Spring", "Обеспечивает интерфейс для взаимодействия пользователя с системой")
    Container(profile, "Сервис авторизации и профиля", "Java, Spring", "Обеспечивает авторизацию пользователя и управление профилем")
}
Container(message_broker, "Message broker", "Apache Kafka", "Служит для асинхронного обмена сообщениями между компонентами")
Rel(user, api_gateway, "Взаимодействует через REST API")
Rel(api_gateway, web_app, "Маршрутизирует запросы к веб-приложению")
Rel(api_gateway, profile, "Авторизация")
Rel(web_app, message_broker, "Отправляет команды и запросы через Kafka")
Rel(web_app, profile, "Управляет профилем пользователя")

System_Boundary(BE, "Отопление") {
    Container(microservice_heating, "Микросервис управления отоплением", "Java", "Реализует логику управления отоплением")
    Container(db_heating, "База данных", "Postgres", "Сохраняет информацию об отоплении")
}
System_Ext(heating_system, "Система отопления", "Управляет физическим отоплением в доме")
Rel(message_broker, microservice_heating, "Передает команды управления отоплением")
Rel(microservice_heating, message_broker, "Отправляет обработанные данные")
Rel(microservice_heating, heating_system, "Управляет системой отопления")
Rel(message_broker, web_app, "Передает обработанные данные")


System_Boundary(BEL, "Свет") {
    Container(microservice_light, "Микросервис управления светом", "Java", "Реализует логику управления освещением")
    Container(db_light, "База данных", "Postgres", "Сохраняет информацию об освещении")
}
System_Ext(lights, "Освещение")
Rel(message_broker, microservice_light, "Передает команды управления освещением")
Rel(microservice_light, message_broker, "Отправляет обработанные данные")
Rel(microservice_light, lights, "Вкл/Выкл освещение")


System_Boundary(BEV, "Ворота") {
    Container(microservice_gates, "Микросервис управления воротами", "Java", "Реализует логику управления воротами")
    Container(db_gates, "База данных", "Postgres", "Сохраняет информацию о состоянии ворот")
}
System_Ext(gates, "Ворота")
Rel(message_broker, microservice_gates, "Передает команды управления освещением")
Rel(microservice_gates, message_broker, "Отправляет обработанные данные")
Rel(microservice_gates, gates, "Открыть/Закрыть вопрота")



System_Boundary(BETV, "Видеоаналитика") {
    Container(microservice_tv, "Микросервис управления камерами", "Java", "Реализует логику управления камерами")
    Container(db_tv, "База данных", "Postgres", "Сохраняет данные о камерах")
    Container(db_tv_mongo, "База данных", "MongoDB", "Сохраняет записи с камер")
}
System_Ext(tv, "Камеры")
Rel(message_broker, microservice_tv, "Передает команды управления камерами")
Rel(microservice_tv, message_broker, "Отправляет обработанные данные")
Rel(microservice_tv, tv, "Управление камерами")



System_Boundary(BED, "Датчики") {
    Container(microservice_monitoring, "Микросервис мониторинга датчиков", "Java", "Обрабатывает данные с датчиков")
    Container(db_sensors, "База данных", "Postgres", "Сохраняет информацию с датчиков")
}
System_Ext(temp_sensors, "Датчики температуры", "Собирают данные о температуре в доме")
Rel(message_broker, microservice_monitoring, "Передает запросы для обработки данных о температуре")
Rel(temp_sensors, microservice_monitoring, "Передают данные с датчиков")
Rel(microservice_monitoring, message_broker, "Отправляет обработанные данные")


System_Boundary(BES, "Сценарии") {
    Container(microservice_s, "Микросервис управления сценариями", "Java", "Реализует логику управления сценариями пользователем")
    Container(db_s, "База данных", "MongoDB", "Сохраняет данные по сценариям")
}
Rel(microservice_s, message_broker, "Передает команды управления другими устройствами")
Rel(message_broker, microservice_s, "Отправляет обработанные данные")


System_Boundary(BEA, "Уведомления") {
    Container(microservice_a, "Микросервис управления уведомлениями", "Java", "Реализует логику уведомлений")
    Container(db_a, "База данных", "Postgres", "Сохраняет данные по уведомлениям")
    Container(sms, "Смс сервис", "Java", "Отправляет уведомления по смс")
    Container(mail, "Почтовый сервис", "Java", "Отправляет уведомления по почте")
}
System_Ext(sms_operator, "Оператор СМС", "Отправляет СМС")
Rel(message_broker, microservice_a, "Отправляет запрос на уведомление")
Rel(microservice_a, message_broker, "Отчитывается об уведомлениях")
Rel(sms, sms_operator, "Запрос на отправку СМС")

}
@enduml